version: '3.1'
services:
  api:
    build: .
    command: npm run start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - zaalDB
    volumes:
      - ./src:/usr/app/src:ro
    env_file: '.env'

  zaalDB:
    image: postgres
    restart: always
    env_file: '.env'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:80
